name: Sync labels
on:
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EndBug/label-sync@v2
        with:
          config-file: "https://raw.githubusercontent.com/babyico/.github/master/.github/labels.yml"
          delete-other-labels: true
          token: ${{ secrets.TOKEN }}
